export interface Term {
  term: string;
  def: string;
  cat: "core" | "offense" | "defense" | "governance" | "cloud";
}

export const glossary: Term[] = [
  { term: "Active Directory (AD)", def: "Microsoft identity store for users, computers and groups; prime target when breached (one credential can walk the domain).", cat: "core" },
  { term: "APT (Advanced Persistent Threat)", def: "A well-resourced adversary (often nation-state) that maintains long-term access to a target.", cat: "offense" },
  { term: "ARP Spoofing", def: "MITM technique: replies to ARP requests with a fake MAC so traffic flows through the attacker.", cat: "offense" },
  { term: "ATT&CK", def: "MITRE's knowledge base of attacker tactics and techniques — the shared language of detection mapping.", cat: "core" },
  { term: "Authentication", def: "Proving you are who you claim to be (something you know/have/are).", cat: "core" },
  { term: "Authorization", def: "Deciding what an authenticated user is allowed to do.", cat: "core" },
  { term: "Backdoor", def: "Hidden way into a system, planted by attackers or left by design.", cat: "offense" },
  { term: "Beaconing", def: "Periodic outbound connection to C2; the heartbeat of compromised hosts, and its most detectable signature.", cat: "defense" },
  { term: "Burp Suite", def: "Web proxy used to intercept, modify and replay HTTP traffic — the pentester's web Swiss army knife.", cat: "offense" },
  { term: "C2 (Command & Control)", def: "The attacker's channel to infected machines — issuing orders and receiving stolen data.", cat: "core" },
  { term: "CFAA", def: "US Computer Fraud and Abuse Act — the law that makes unauthorized access a crime; the legal boundary for pentesting.", cat: "governance" },
  { term: "CIA Triad", def: "Confidentiality, Integrity, Availability — the three security goals every control serves.", cat: "core" },
  { term: "CIS Controls", def: "18 prioritized operational security controls; the actionable 'do these first' list.", cat: "governance" },
  { term: "CISA KEV", def: "Known Exploited Vulnerabilities catalog: CVEs with confirmed public exploitation. Fix these first.", cat: "defense" },
  { term: "Cloud Metadata Service", def: "Internal IP (e.g. 169.254.169.254) holding cloud credentials; SSRF attacks aim here.", cat: "cloud" },
  { term: "Credential Stuffing", def: "Replaying breached username/password pairs across services (reuse makes it work).", cat: "offense" },
  { term: "Cross-Site Scripting (XSS)", def: "Injecting client-side script that runs in victims' browsers — steals sessions, hijacks accounts.", cat: "offense" },
  { term: "CSI / CSIRT", def: "Computer Security Incident Response Team.", cat: "defense" },
  { term: "CVSS", def: "Common Vulnerability Scoring System — 0-10 severity number for a vulnerability (context still decides risk).", cat: "defense" },
  { term: "DMARC", def: "DNS policy telling receivers what to do with email that fails SPF/DKIM — the spoofing killer.", cat: "defense" },
  { term: "DNS Rebinding", def: "Alternating DNS answers to bypass SSRF/IP allowlists — the 'flip-flop' attack.", cat: "offense" },
  { term: "EDR", def: "Endpoint Detection & Response: collects endpoint telemetry and enables response actions.", cat: "defense" },
  { term: "Elimination", def: "Removing the attacker entirely: malware, persistence, root cause.", cat: "defense" },
  { term: "Encryption at Rest", def: "Encrypting stored data so a stolen disk is gibberish without the key.", cat: "core" },
  { term: "Encryption in Transit", def: "Encrypting data while it travels (TLS/HTTPS).", cat: "core" },
  { term: "EPSS", def: "Exploit Prediction Scoring System — statistical probability a CVE gets exploited in the next 30 days.", cat: "defense" },
  { term: "Exploit", def: "Code or technique that takes advantage of a vulnerability.", cat: "offense" },
  { term: "FIM (File Integrity Monitoring)", def: "Detecting changes to critical files — config drift or tampering alarms.", cat: "defense" },
  { term: "Firewall", def: "Enforces allow/deny of traffic based on rules — zones are made of these.", cat: "defense" },
  { term: "GDPR", def: "EU data protection law: rights, consent, 72h breach notification, huge fines.", cat: "governance" },
  { term: "Hash (cryptographic)", def: "One-way fingerprint of data (SHA-256); file identity, evidence integrity, password storage.", cat: "core" },
  { term: "Honeypot", def: "Deliberately vulnerable system that traps attackers and reveals their playbook.", cat: "defense" },
  { term: "HSTS", def: "Strict-Transport-Security header forcing browsers to HTTPS — kills SSL-stripping.", cat: "defense" },
  { term: "IAM", def: "Identity and Access Management — who is who and what they can do, across IT and cloud.", cat: "core" },
  { term: "IEC 62443", def: "The international standard for industrial/ICS (OT) cybersecurity: zones & conduits.", cat: "governance" },
  { term: "IOC (Indicator of Compromise)", def: "Artifact of an intrusion (hash, IP, domain). Fast to find, fast to change.", cat: "defense" },
  { term: "Incident Response", def: "Process for handling a confirmed breach: prepare, detect, contain, eradicate, recover, learn.", cat: "defense" },
  { term: "Indicators of Attack (IOA)", def: "Behavioral evidence an attack is happening, versus IOCs which are after-the-fact.", cat: "defense" },
  { term: "Injection", def: "Sending malicious input (SQL, commands, scripts) that the app executes as code.", cat: "offense" },
  { term: "ISO 27001", def: "Certifiable information security management system standard (ISMS).", cat: "governance" },
  { term: "Kerberos", def: "AD's default auth protocol; targeted by pass-the-ticket/Golden Ticket attacks.", cat: "core" },
  { term: "Kill Chain", def: "Attack stages: delivery → execution → persistence → C2 → action. Each stage = detection point.", cat: "defense" },
  { term: "Least Privilege", def: "Grant only the minimum access needed for a task — limits blast radius.", cat: "core" },
  { term: "LOLBins", def: "Legitimate binaries (powershell, bitsadmin) abused for malicious actions — 'living off the land'.", cat: "offense" },
  { term: "Malware", def: "Malicious software: viruses, worms, trojans, ransomware, rootkits, spyware.", cat: "offense" },
  { term: "Man-in-the-Middle (MITM)", def: "Attacker inserts themself between two parties, reading or modifying traffic.", cat: "offense" },
  { term: "Metasploit", def: "Exploit development framework — modules, payloads, post-exploitation.", cat: "offense" },
  { term: "MFA", def: "Multi-Factor Authentication: two+ proof types; kills most credential-based attacks.", cat: "core" },
  { term: "MITRE ATT&CK", def: "Global framework of adversary tactics & techniques (see ATT&CK).", cat: "core" },
  { term: "MSP", def: "Managed Service Provider — outsourced IT/security; attacks now arrive via the MSP.", cat: "defense" },
  { term: "MTTD / MTTR", def: "Mean Time to Detect / Respond — the SOC's core performance metrics.", cat: "defense" },
  { term: "NIST CSF", def: "US cybersecurity framework: Govern, Identify, Protect, Detect, Respond, Recover.", cat: "governance" },
  { term: "Nmap", def: "Network scanner mapping hosts, ports, services and OS — recon step one.", cat: "offense" },
  { term: "OSINT", def: "Open Source Intelligence: public info (DNS, WHOIS, socials, GitHub) gathered passively.", cat: "offense" },
  { term: "OWASP Top 10", def: "The ranked list of most critical web application security risks.", cat: "offense" },
  { term: "Pass-the-Hash", def: "Using a captured NTLM hash to authenticate without the plaintext password.", cat: "offense" },
  { term: "PCI DSS", def: "Contractual standard for payment card data security (12 requirements).", cat: "governance" },
  { term: "Pentest (Penetration Test)", def: "Authorized simulation of attack to find and document weaknesses.", cat: "offense" },
  { term: "Phishing", def: "Fraudulent messages tricking users into giving credentials or running malware.", cat: "offense" },
  { term: "Playbook", def: "Step-by-step documented response procedure for a scenario.", cat: "defense" },
  { term: "Pwned Password", def: "A password known from a breach; denies password reuse effectively.", cat: "core" },
  { term: "Red Team / Blue Team", def: "Offensive testers vs. defenders; exercise the two halves of security.", cat: "core" },
  { term: "Risk", def: "Likelihood × Impact of a threat exploiting a vulnerability against an asset.", cat: "governance" },
  { term: "RPO / RTO", def: "Recovery Point Objective (how much data you accept losing) / Recovery Time Objective (downtime budget).", cat: "defense" },
  { term: "Ransomware", def: "Malware that encrypts data and extorts payment; frequently double-extortion + exfiltration.", cat: "offense" },
  { term: "Reconnaissance", def: "Gathering info about a target before attacking (passive → active).", cat: "offense" },
  { term: "Reverse Shell", def: "Victim initiates connection back to the attacker's listener.", cat: "offense" },
  { term: "Rootkit", def: "Malware that conceals its own and other processes from detection.", cat: "offense" },
  { term: "Rules of Engagement (RoE)", def: "Written scope/limits of a test — the document that makes testing legal.", cat: "governance" },
  { term: "SAST / DAST", def: "Static vs Dynamic Application Security Testing — scan code vs. scan running app.", cat: "cloud" },
  { term: "SCA", def: "Software Composition Analysis — scanning dependencies for known CVEs.", cat: "cloud" },
  { term: "Secrets Management", def: "Storing keys/tokens in a vault with rotation instead of in code or configs.", cat: "cloud" },
  { term: "Shared Responsibility", def: "Cloud model: provider secures the infrastructure; YOU secure what you rent.", cat: "cloud" },
  { term: "SIEM", def: "Security Information & Event Management — central log store, correlation, alerts.", cat: "defense" },
  { term: "Sigma", def: "Open signature format for detection rules, runnable across SIEMs.", cat: "defense" },
  { term: "Smishing", def: "Phishing over SMS.", cat: "offense" },
  { term: "SOAR", def: "Security Orchestration, Automation & Response — playbooks run by machines.", cat: "defense" },
  { term: "SOC", def: "Security Operations Center: the team that monitors/detects/responds.", cat: "defense" },
  { term: "SOC 2", def: "Auditor attestation of service organization controls (Security, Availability, etc.).", cat: "governance" },
  { term: "Splunk / Elk", def: "Popular SIEM/log platforms (SPL query language / Elastic stack).", cat: "defense" },
  { term: "SQL Injection", def: "Injecting malformed SQL through input to read/write the database.", cat: "offense" },
  { term: "SSRF", def: "Server-Side Request Forgery: making the server fetch attacker URLs (→ metadata, internal).", cat: "offense" },
  { term: "Threat Intelligence", def: "Actionable, analyzed info about adversaries relevant to your posture.", cat: "defense" },
  { term: "Threat Model", def: "Structured view of what you protect, against whom, via what paths.", cat: "governance" },
  { term: "TTP", def: "Tactics, Techniques, Procedures — how an adversary operates (behavior, vs. IOCs).", cat: "core" },
  { term: "Vishing", def: "Phishing over voice calls.", cat: "offense" },
  { term: "Vulnerability", def: "A weakness that can be exploited. Combination: threat + vulnerability + asset = risk.", cat: "core" },
  { term: "WAF", def: "Web Application Firewall — filters HTTP/SQLi/XSS-style payloads in front of apps.", cat: "defense" },
  { term: "YARA", def: "Pattern-matching language for malware detection rules.", cat: "defense" },
  { term: "Zero Day", def: "A vulnerability unknown to the vendor, so no patch exists yet — hence this site's name.", cat: "core" },
  { term: "Zero Trust", def: "'Never trust, always verify' — identity-first, micro-segmented, continuously validated.", cat: "core" },
  { term: "Defense in Depth", def: "Layering independent controls so one failure doesn't mean compromise.", cat: "core" },
  { term: "Attack Surface", def: "Every path an attacker can reach: ports, apps, APIs, humans, cloud metadata.", cat: "core" },
  { term: "Trust Boundary", def: "The point where a higher trust zone meets a lower-trust input (user input crossing into a database).", cat: "core" },
  { term: "Baseline", def: "The documented 'normal' state of a system/config you compare anomalies against.", cat: "defense" },
  { term: "Compensating Control", def: "An alternative control used when the primary one can't be implemented.", cat: "governance" },
  { term: "Security Posture", def: "An organization's overall readiness to resist attacks and respond to them.", cat: "core" },
  { term: "STRIDE", def: "Spoofing, Tampering, Repudiation, Info disclosure, DoS, Escalation — the classic threat-modeling mnemonic.", cat: "core" },
  { term: "DREAD", def: "Damage, Reproducibility, Exploitability, Affected users, Discoverability — risk scoring for threats.", cat: "core" },
  { term: "Threat Modeling", def: "Structured process to identify threats against a system before attackers do.", cat: "core" },
  { term: "Data Flow Diagram (DFD)", def: "How data moves through a system — the base for spotting trust boundaries in threat models.", cat: "core" },
  { term: "SAML", def: "XML-based SSO protocol; federation between identity providers and apps.", cat: "core" },
  { term: "OIDC", def: "OAuth 2.0 + ID tokens; the modern web SSO protocol.", cat: "core" },
  { term: "JWT", def: "JSON Web Token — signed claims used for auth/session; keep the signing secret secret.", cat: "core" },
  { term: "Secure SDLC", def: "Building security into every software phase rather than bolting it on at the end.", cat: "cloud" },
  { term: "Shift Left", def: "Moving security/testing earlier in the pipeline (code over production).", cat: "cloud" },
  { term: "SBOM", def: "Software Bill of Materials — the inventory of third-party packages in a product.", cat: "cloud" },
  { term: "IaC", def: "Infrastructure as Code — servers/config defined in version-controlled files.", cat: "cloud" },
  { term: "DevSecOps Feedback Loop", def: "Rapid failure feedback from security tests into developers' merge requests.", cat: "cloud" },
  { term: "PTES", def: "Penetration Testing Execution Standard — a methodology for structured pentests.", cat: "governance" },
  { term: "OSSTMM", def: "Open Source Security Testing Methodology Manual — another formal pentest standard.", cat: "governance" },
  { term: "Deconfliction", def: "Coordination to stop a red-team action from tripping a real incident or hurting production.", cat: "governance" },
  { term: "CTF", def: "Capture the Flag — a safe game of offensive/defensive cyber skills.", cat: "offense" },
  { term: "Kali Linux", def: "Debian-based distro preloaded with hundreds of offensive security tools.", cat: "offense" },
  { term: "VirtualBox", def: "Free host-based hypervisor; the standard home-lab GPU for Kali + targets.", cat: "offense" },
  { term: "Wireshark", def: "Packet-capture analysis tool; 'see the traffic' for Ethernet, Wi-Fi and USB.", cat: "offense" },
  { term: "Aircrack-ng", def: "Wireless toolkit: capture, deauth, crack WEP/WPA keys.", cat: "offense" },
  { term: "John the Ripper", def: "Offline password cracker (CPU-optimized) with many hash formats.", cat: "offense" },
  { term: "Hashcat", def: "GPU-accelerated password cracker — the speed king in hash cracking.", cat: "offense" },
  { term: "sqlmap", def: "Automated SQL injection detection/exploitation tool.", cat: "offense" },
  { term: "Nikto", def: "Web server scanner hunting misconfigs and known-vulnerable files.", cat: "offense" },
  { term: "enum4linux", def: "Extracts users, shares, and policies from SMB/Windows hosts.", cat: "offense" },
  { term: "Shodan", def: "Internet-wide search engine for exposed devices and services.", cat: "offense" },
  { term: "Google Dorking", def: "Using advanced search operators (filetype: site: inurl:) for passive recon.", cat: "offense" },
  { term: "theHarvester", def: "OSINT tool pulling emails/subdomains from search engines and services.", cat: "offense" },
  { term: "Maltego", def: "Link-analysis graph tool for mapping OSINT relationships.", cat: "offense" },
  { term: "WHOIS", def: "Public registration data for domains/IPs — owner, dates, nameservers.", cat: "offense" },
  { term: "Privilege Escalation", def: "Turning limited access into more (user→admin→SYSTEM/root).", cat: "offense" },
  { term: "UAC", def: "Windows User Account Control — the consent prompt protecting admin rights.", cat: "defense" },
  { term: "DLL Injection", def: "Forcing a process to load an attacker DLL — stealthy code execution.", cat: "offense" },
  { term: "Process Injection", def: "Running malicious code inside a legitimate process to hide it.", cat: "offense" },
  { term: "Fileless Malware", def: "Attacks that execute in-memory (PowerShell/macros) with no file on disk.", cat: "offense" },
  { term: "AMSI", def: "Windows Anti-Malware Scan Interface — lets AV/EDR inspect PowerShell/JScript activity.", cat: "defense" },
  { term: "AppLocker", def: "Windows application allowlisting to block unauthorized executables.", cat: "defense" },
  { term: "DHCP Starvation", def: "Exhausting the DHCP pool so legit devices can't get addresses.", cat: "offense" },
  { term: "VLAN Hopping", def: "Pivoting between VLANs via trunk/double-tagging tricks.", cat: "offense" },
  { term: "MAC Flooding", def: "Overwhelming a switch's CAM table to turn it into a hub.", cat: "offense" },
  { term: "CSRF", def: "Cross-Site Request Forgery: making a logged-in user's browser send unwanted requests.", cat: "offense" },
  { term: "LFI / RFI", def: "Local/Remote File Include: reading or executing files via unvalidated paths.", cat: "offense" },
  { term: "XXE", def: "XML External Entity: abusing XML parsers to read files or SSRF.", cat: "offense" },
  { term: "SSTI", def: "Server-Side Template Injection: attacker code runs in the template engine.", cat: "offense" },
  { term: "Insecure Deserialization", def: "Untrusted data rebuilt into objects → RCE or tampering.", cat: "offense" },
  { term: "Broken Access Control", def: "Missing authorization checks let users touch what they shouldn't (OWASP #1).", cat: "offense" },
  { term: "Amplification Attack", def: "Small request → large response (NTP/DNS) flooding a victim.", cat: "offense" },
  { term: "SYN Flood", def: "Half-open TCP connections exhausting a server's backlog.", cat: "offense" },
  { term: "Tearing / Evasion", def: "Fragmentation, encoding or timing tricks to slip past IDS signatures.", cat: "offense" },
  { term: "Padding Oracle Attack", def: "Using a server's 'invalid padding' response to decrypt CBC ciphertext.", cat: "offense" },
  { term: "ECB Mode", def: "CBC is gone; ECB repeats identical plaintext blocks — a visible weakness in patterns.", cat: "core" },
  { term: "Side-Channel Attack", def: "Extracting secrets from timing, power, EM or cache behavior — not the algorithm.", cat: "offense" },
  { term: "Rainbow Table", def: "Precomputed hash→password lookup tables; defeated by salting.", cat: "offense" },
  { term: "KDF", def: "Key Derivation Function (PBKDF2, Argon2) — slow hashing for passwords + session keys.", cat: "core" },
  { term: "Salt", def: "Per-user random value mixed into password hashing; kills rainbow tables and identical-hash links.", cat: "core" },
  { term: "Nonce", def: "Number used once — freshness proof in crypto protocols.", cat: "core" },
  { term: "CTI", def: "Cyber Threat Intelligence — analyzed, actionable adversary information.", cat: "defense" },
  { term: "Diamond Model", def: "Adversary-Capability-Infrastructure-Victim relationship model for intrusion analysis.", cat: "defense" },
  { term: "STIX / TAXII", def: "Structured Threat Info eXpression + Transport: standards to share CTI machine-to-machine.", cat: "defense" },
  { term: "Runbook", def: "Automated or documented step sequence for a repeatable task.", cat: "defense" },
  { term: "Sysmon", def: "Windows telemetry driver logging process, network, registry and file events in depth.", cat: "defense" },
  { term: "XDR", def: "Extended Detection & Response — cross-correlating endpoint, network and identity telemetry.", cat: "defense" },
  { term: "OSQuery", def: "SQL-queryable endpoint inventory across fleets of hosts.", cat: "defense" },
  { term: "NGFW", def: "Next-Gen Firewall — app-aware, identity-aware firewall with IPS/SSL inspection.", cat: "defense" },
  { term: "Suricata", def: "Open-source NIDS/IPS with Lua scripting and multithreaded matching.", cat: "defense" },
  { term: "ModSecurity", def: "Open-source WAF engine for Apache/nginx; often paired with OWASP CRS.", cat: "defense" },
  { term: "CRS", def: "OWASP Core Rule Set — ~2,000 generic WAF rules for web attacks.", cat: "defense" },
  { term: "Virtual Patching", def: "A WAF/IPS rule blocking an exploit before the software patch lands.", cat: "defense" },
  { term: "ZTNA", def: "Zero Trust Network Access — per-app, identity-based access instead of network-wide VPN.", cat: "defense" },
  { term: "WireGuard", def: "Modern, fast, audited VPN protocol with crypto-curve keys.", cat: "defense" },
  { term: "NetFlow / sFlow", def: "Network flow records: src, dst, ports, bytes — cheap metadata for traffic analysis.", cat: "defense" },
  { term: "Zeek", def: "Network security monitor producing rich per-protocol connection logs.", cat: "defense" },
  { term: "RPZ", def: "Response Policy Zone — DNS-level filtering to block malicious resolvers/domains at most.", cat: "defense" },
  { term: "SASE", def: "Secure Access Service Edge — networking + security converged in a cloud edge.", cat: "defense" },
  { term: "BIA", def: "Business Impact Analysis — quantifying downtime and data-loss costs per function.", cat: "governance" },
  { term: "FAIR", def: "Factor Analysis of Information Risk — quantitative risk analysis in monetary terms.", cat: "governance" },
  { term: "ALE", def: "Annualized Loss Expectancy — expected $ loss per risk per year; risk quantification.", cat: "governance" },
  { term: "Risk Register", def: "Living list of risks: owner, score, controls, residual, decision, review date.", cat: "governance" },
  { term: "Risk Appetite", def: "How much risk an organization formally accepts to reach its goals.", cat: "governance" },
  { term: "Cyber Insurance", def: "Transferring cyber risk to an insurer; premiums conditioned on your controls.", cat: "governance" },
  { term: "SPF / DKIM", def: "Email sender authentication: SPF allowlist IPs, DKIM signs the mail.", cat: "defense" },
  { term: "Tabletop Exercise", def: "Low-cost walkthrough of a scenario to test people and decisions.", cat: "governance" },
  { term: "Cobalt Strike", def: "Commercial red-team C2 framework (beacons, malleable C2).", cat: "offense" },
  { term: "Sliver", def: "Open-source C2 framework for emulation — the free practitioner's beacon.", cat: "offense" },
  { term: "Beacon", def: "C2 implant that sleeps then connects out; sleep/jitter make it stealthy.", cat: "offense" },
  { term: "Persistence", def: "Mechanisms to survive reboots and stay resident (Run keys, scheduled tasks, services).", cat: "offense" },
  { term: "Golden Ticket", def: "Forged Kerberos TGT with krbtgt key — total domain impersonation.", cat: "offense" },
  { term: "Ghidra", def: "Free NSA reverse-engineering suite: disassembly + decompiler.", cat: "offense" },
  { term: "IDA Pro", def: "Commercial disassembler; the decompiler benchmark in malware analysis.", cat: "offense" },
  { term: "objdump / readelf", def: "ELF binary inspection utilities: sections, symbols, disassembly.", cat: "offense" },
  { term: "GDB", def: "GNU debugger — breakpoints, registers, stepping through the exact code path.", cat: "offense" },
  { term: "Shellcode", def: "Machine-code payload that spawns a shell (or worse).", cat: "offense" },
  { term: "Buffer Overflow", def: "Writing past a buffer's bounds to corrupt adjacent memory.", cat: "offense" },
  { term: "NOP Sled", def: "Run of NOP instructions letting execution slide into payload.", cat: "offense" },
  { term: "ASLR", def: "Address Space Layout Randomization — randomizes memory bases to break guessable jumps.", cat: "defense" },
  { term: "NX / DEP", def: "Non-Executable memory stack — stops shellcode running directly.", cat: "defense" },
  { term: "Stack Canary", def: "Random value before the return address; corrupted = crash instead of control.", cat: "defense" },
  { term: "PIE", def: "Position Independent Executable — code+data bases randomized; stops static-address exploits.", cat: "defense" },
  { term: "RELRO", def: "Read-Only RELocations — protects the GOT from arbitrary write attacks.", cat: "defense" },
  { term: "ROP", def: "Return-Oriented Programming — chaining existing code gadgets to take control.", cat: "offense" },
  { term: "Ret2libc", def: "Returning to libc functions (system) instead of executing injected code.", cat: "offense" },
  { term: "Format String Attack", def: "User-controlled printf format — read/write arbitrary memory via %n/%s.", cat: "offense" },
  { term: "Fuzzing", def: "Feeding malformed inputs to a program until it misbehaves; source of most bug discoveries.", cat: "offense" },
  { term: "AFL++", def: "Coverage-guided fuzzer — the standard for finding bugs fast.", cat: "offense" },
  { term: "pwntools", def: "Python library for precise exploit payloads and ROP chain building.", cat: "offense" },
  { term: "Quantum (PQC)", def: "Post-quantum cryptography — NIST schemes (Kyber/ML-KEM, Dilithium/ML-DSA) resist Shor QC.", cat: "core" },
  { term: "Shor's Algorithm", def: "Quantum algorithm that would break RSA/ECC factoring/discrete log.", cat: "core" },
  { term: "Harvest-Now-Decrypt-Later", def: "Adversary captures encrypted data now, decrypts when QC arrives — act early on long-lived secrets.", cat: "defense" },
  { term: "UEBA", def: "User & Entity Behavior Analytics — ML-drift detection on user/device behavior.", cat: "defense" },
  { term: "Deepfake", def: "Synthetic audio/video of a real person — the new vishing weapon.", cat: "offense" },
  { term: "C2PA", def: "Coalition for Content Provenance & Authenticity — metadata to trace media origin.", cat: "governance" },
  { term: "STIR/SHAKEN", def: "Caller-ID authentication framework to stop spoofed phone numbers.", cat: "defense" },
];

export const categories: Record<Term["cat"], string> = {
  core: "Core Concepts",
  offense: "Offense / Attacks",
  defense: "Defense / Operations",
  governance: "Governance & Compliance",
  cloud: "Cloud & DevSecOps",
};

export function slugifyTerm(term: string): string {
  return term.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}