export interface Term {
  term: string;
  def: string;
  cat: "core" | "offense" | "defense" | "governance" | "cloud";
}

export const glossary: Term[] = [
  { term: "Active Directory (AD)", def: "Microsoft identity store for users, computers and groups; prime target when breached (one credential can walk the domain).", cat: "core" },
  { term: "APT (Advanced Persistent Threat)", def: "A well-resourced adversary (often nation-state) that maintains long-term access to a target.", cat: "offense" },
  { term: "ARP Spoofing", def: "MITM technique: replies to ARP requests with a fake MAC so traffic flows through the attacker.", cat: "offense" },
  { term: "ATT&CK", def: "MITRE's knowledge base of attacker tactics and techniques — the shared language of detection mapping.", cat: "core" },
  { term: "Authentication", def: "Proving you are who you claim to be (something you know/have/are).", cat: "core" },
  { term: "Authorization", def: "Deciding what an authenticated user is allowed to do.", cat: "core" },
  { term: "Backdoor", def: "Hidden way into a system, planted by attackers or left by design.", cat: "offense" },
  { term: "Beaconing", def: "Periodic outbound connection to C2; the heartbeat of compromised hosts, and its most detectable signature.", cat: "defense" },
  { term: "Burp Suite", def: "Web proxy used to intercept, modify and replay HTTP traffic — the pentester's web Swiss army knife.", cat: "offense" },
  { term: "C2 (Command & Control)", def: "The attacker's channel to infected machines — issuing orders and receiving stolen data.", cat: "core" },
  { term: "CFAA", def: "US Computer Fraud and Abuse Act — the law that makes unauthorized access a crime; the legal boundary for pentesting.", cat: "governance" },
  { term: "CIA Triad", def: "Confidentiality, Integrity, Availability — the three security goals every control serves.", cat: "core" },
  { term: "CIS Controls", def: "18 prioritized operational security controls; the actionable 'do these first' list.", cat: "governance" },
  { term: "CISA KEV", def: "Known Exploited Vulnerabilities catalog: CVEs with confirmed public exploitation. Fix these first.", cat: "defense" },
  { term: "Cloud Metadata Service", def: "Internal IP (e.g. 169.254.169.254) holding cloud credentials; SSRF attacks aim here.", cat: "cloud" },
  { term: "Credential Stuffing", def: "Replaying breached username/password pairs across services (reuse makes it work).", cat: "offense" },
  { term: "Cross-Site Scripting (XSS)", def: "Injecting client-side script that runs in victims' browsers — steals sessions, hijacks accounts.", cat: "offense" },
  { term: "CSI / CSIRT", def: "Computer Security Incident Response Team.", cat: "defense" },
  { term: "CVSS", def: "Common Vulnerability Scoring System — 0-10 severity number for a vulnerability (context still decides risk).", cat: "defense" },
  { term: "DMARC", def: "DNS policy telling receivers what to do with email that fails SPF/DKIM — the spoofing killer.", cat: "defense" },
  { term: "DNS Rebinding", def: "Alternating DNS answers to bypass SSRF/IP allowlists — the 'flip-flop' attack.", cat: "offense" },
  { term: "EDR", def: "Endpoint Detection & Response: collects endpoint telemetry and enables response actions.", cat: "defense" },
  { term: "Elimination", def: "Removing the attacker entirely: malware, persistence, root cause.", cat: "defense" },
  { term: "Encryption at Rest", def: "Encrypting stored data so a stolen disk is gibberish without the key.", cat: "core" },
  { term: "Encryption in Transit", def: "Encrypting data while it travels (TLS/HTTPS).", cat: "core" },
  { term: "EPSS", def: "Exploit Prediction Scoring System — statistical probability a CVE gets exploited in the next 30 days.", cat: "defense" },
  { term: "Exploit", def: "Code or technique that takes advantage of a vulnerability.", cat: "offense" },
  { term: "FIM (File Integrity Monitoring)", def: "Detecting changes to critical files — config drift or tampering alarms.", cat: "defense" },
  { term: "Firewall", def: "Enforces allow/deny of traffic based on rules — zones are made of these.", cat: "defense" },
  { term: "GDPR", def: "EU data protection law: rights, consent, 72h breach notification, huge fines.", cat: "governance" },
  { term: "Hash (cryptographic)", def: "One-way fingerprint of data (SHA-256); file identity, evidence integrity, password storage.", cat: "core" },
  { term: "Honeypot", def: "Deliberately vulnerable system that traps attackers and reveals their playbook.", cat: "defense" },
  { term: "HSTS", def: "Strict-Transport-Security header forcing browsers to HTTPS — kills SSL-stripping.", cat: "defense" },
  { term: "IAM", def: "Identity and Access Management — who is who and what they can do, across IT and cloud.", cat: "core" },
  { term: "IEC 62443", def: "The international standard for industrial/ICS (OT) cybersecurity: zones & conduits.", cat: "governance" },
  { term: "IOC (Indicator of Compromise)", def: "Artifact of an intrusion (hash, IP, domain). Fast to find, fast to change.", cat: "defense" },
  { term: "Incident Response", def: "Process for handling a confirmed breach: prepare, detect, contain, eradicate, recover, learn.", cat: "defense" },
  { term: "Indicators of Attack (IOA)", def: "Behavioral evidence an attack is happening, versus IOCs which are after-the-fact.", cat: "defense" },
  { term: "Injection", def: "Sending malicious input (SQL, commands, scripts) that the app executes as code.", cat: "offense" },
  { term: "ISO 27001", def: "Certifiable information security management system standard (ISMS).", cat: "governance" },
  { term: "Kerberos", def: "AD's default auth protocol; targeted by pass-the-ticket/Golden Ticket attacks.", cat: "core" },
  { term: "Kill Chain", def: "Attack stages: delivery → execution → persistence → C2 → action. Each stage = detection point.", cat: "defense" },
  { term: "Least Privilege", def: "Grant only the minimum access needed for a task — limits blast radius.", cat: "core" },
  { term: "LOLBins", def: "Legitimate binaries (powershell, bitsadmin) abused for malicious actions — 'living off the land'.", cat: "offense" },
  { term: "Malware", def: "Malicious software: viruses, worms, trojans, ransomware, rootkits, spyware.", cat: "offense" },
  { term: "Man-in-the-Middle (MITM)", def: "Attacker inserts themself between two parties, reading or modifying traffic.", cat: "offense" },
  { term: "Metasploit", def: "Exploit development framework — modules, payloads, post-exploitation.", cat: "offense" },
  { term: "MFA", def: "Multi-Factor Authentication: two+ proof types; kills most credential-based attacks.", cat: "core" },
  { term: "MITRE ATT&CK", def: "Global framework of adversary tactics & techniques (see ATT&CK).", cat: "core" },
  { term: "MSP", def: "Managed Service Provider — outsourced IT/security; attacks now arrive via the MSP.", cat: "defense" },
  { term: "MTTD / MTTR", def: "Mean Time to Detect / Respond — the SOC's core performance metrics.", cat: "defense" },
  { term: "NIST CSF", def: "US cybersecurity framework: Govern, Identify, Protect, Detect, Respond, Recover.", cat: "governance" },
  { term: "Nmap", def: "Network scanner mapping hosts, ports, services and OS — recon step one.", cat: "offense" },
  { term: "OSINT", def: "Open Source Intelligence: public info (DNS, WHOIS, socials, GitHub) gathered passively.", cat: "offense" },
  { term: "OWASP Top 10", def: "The ranked list of most critical web application security risks.", cat: "offense" },
  { term: "Pass-the-Hash", def: "Using a captured NTLM hash to authenticate without the plaintext password.", cat: "offense" },
  { term: "PCI DSS", def: "Contractual standard for payment card data security (12 requirements).", cat: "governance" },
  { term: "Pentest (Penetration Test)", def: "Authorized simulation of attack to find and document weaknesses.", cat: "offense" },
  { term: "Phishing", def: "Fraudulent messages tricking users into giving credentials or running malware.", cat: "offense" },
  { term: "Playbook", def: "Step-by-step documented response procedure for a scenario.", cat: "defense" },
  { term: "Pwned Password", def: "A password known from a breach; denies password reuse effectively.", cat: "core" },
  { term: "Red Team / Blue Team", def: "Offensive testers vs. defenders; exercise the two halves of security.", cat: "core" },
  { term: "Risk", def: "Likelihood × Impact of a threat exploiting a vulnerability against an asset.", cat: "governance" },
  { term: "RPO / RTO", def: "Recovery Point Objective (how much data you accept losing) / Recovery Time Objective (downtime budget).", cat: "defense" },
  { term: "Ransomware", def: "Malware that encrypts data and extorts payment; frequently double-extortion + exfiltration.", cat: "offense" },
  { term: "Reconnaissance", def: "Gathering info about a target before attacking (passive → active).", cat: "offense" },
  { term: "Reverse Shell", def: "Victim initiates connection back to the attacker's listener.", cat: "offense" },
  { term: "Rootkit", def: "Malware that conceals its own and other processes from detection.", cat: "offense" },
  { term: "Rules of Engagement (RoE)", def: "Written scope/limits of a test — the document that makes testing legal.", cat: "governance" },
  { term: "SAST / DAST", def: "Static vs Dynamic Application Security Testing — scan code vs. scan running app.", cat: "cloud" },
  { term: "SCA", def: "Software Composition Analysis — scanning dependencies for known CVEs.", cat: "cloud" },
  { term: "Secrets Management", def: "Storing keys/tokens in a vault with rotation instead of in code or configs.", cat: "cloud" },
  { term: "Shared Responsibility", def: "Cloud model: provider secures the infrastructure; YOU secure what you rent.", cat: "cloud" },
  { term: "SIEM", def: "Security Information & Event Management — central log store, correlation, alerts.", cat: "defense" },
  { term: "Sigma", def: "Open signature format for detection rules, runnable across SIEMs.", cat: "defense" },
  { term: "Smishing", def: "Phishing over SMS.", cat: "offense" },
  { term: "SOAR", def: "Security Orchestration, Automation & Response — playbooks run by machines.", cat: "defense" },
  { term: "SOC", def: "Security Operations Center: the team that monitors/detects/responds.", cat: "defense" },
  { term: "SOC 2", def: "Auditor attestation of service organization controls (Security, Availability, etc.).", cat: "governance" },
  { term: "Splunk / Elk", def: "Popular SIEM/log platforms (SPL query language / Elastic stack).", cat: "defense" },
  { term: "SQL Injection", def: "Injecting malformed SQL through input to read/write the database.", cat: "offense" },
  { term: "SSRF", def: "Server-Side Request Forgery: making the server fetch attacker URLs (→ metadata, internal).", cat: "offense" },
  { term: "Threat Intelligence", def: "Actionable, analyzed info about adversaries relevant to your posture.", cat: "defense" },
  { term: "Threat Model", def: "Structured view of what you protect, against whom, via what paths.", cat: "governance" },
  { term: "TTP", def: "Tactics, Techniques, Procedures — how an adversary operates (behavior, vs. IOCs).", cat: "core" },
  { term: "Vishing", def: "Phishing over voice calls.", cat: "offense" },
  { term: "Vulnerability", def: "A weakness that can be exploited. Combination: threat + vulnerability + asset = risk.", cat: "core" },
  { term: "WAF", def: "Web Application Firewall — filters HTTP/SQLi/XSS-style payloads in front of apps.", cat: "defense" },
  { term: "YARA", def: "Pattern-matching language for malware detection rules.", cat: "defense" },
  { term: "Zero Day", def: "A vulnerability unknown to the vendor, so no patch exists yet — hence this site's name.", cat: "core" },
  { term: "Zero Trust", def: "'Never trust, always verify' — identity-first, micro-segmented, continuously validated.", cat: "core" },
];

export const categories: Record<Term["cat"], string> = {
  core: "Core Concepts",
  offense: "Offense / Attacks",
  defense: "Defense / Operations",
  governance: "Governance & Compliance",
  cloud: "Cloud & DevSecOps",
};

export function slugifyTerm(term: string): string {
  return term.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}